### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by offtel** [domoticafacilconjota/capitulos#72]
.

**Comment by gtrabanco** [comment]
Bom dia.

@domoticafacilconjota decidió hace unos días dejar subir videos a youtube y ha cancelado los miembros. Te sugiero que quites el número de teléfono, en caso de que te conteste, acordar una forma de contacto. Pero no es buena idea compartir datos de contacto privados por aquí.

Por otro lado, puedes preguntar aquí tus dudas en español, portugués (nos entendemos bien, ¡creo!) o inglés. De vez en cuando yo le hecho un vistazo y contesto lo que puedo.

Un saludo.

**Comment by offtel** [comment]
Gtrabanco... Muchas gracias. Yo pensava q solo ele iria ver essa mensage...

**Comment by gtrabanco** [comment]
De nada, pero puedes dejar el mensaje para que si lo lee y quiere contactar te diga como.

Por otro lado insisto en que puedes preguntar todas las dudas aquí.

Por último, si no quieres más ayuda pulsa en cerrar o resuelta la issue por favor.

**Comment by offtel** [comment]
Y tu Eres crack de node red y domótica?

**Comment by offtel** [comment]
Hola Jota.
Soy de Portugal e estou empezando en o mundo de HA.
Hace 2 meses q estou vendo Tus videos. Desde El primero. Adoro.
Hace 2 dias YouTube me devolvio los euros que yo tenia pago para ser teu apoiante em YouTube. porque??
Te queria proponer uma cosa. Que tal dares umas aulas privadas por WhatsApp ou outra forma, de manera que yo aprenda mas rápido , pois tengo uma casa en construcion y necessito saber por donde empezar.
Yo me parece q soy hábil con esas cosas, pero queria una ayuda. Entendo que seria algo que ocuparia tu tiempo y por eso teria de ser pago, y yo quero pagar. Me dices in valor/ hora , por favor... .te pagaria por transferência, por PayPal ou revolut, como quieras. A mi me parece q con 2 ou 3 horas máximo entrare em um ritmo que despues puedo seguir solo.
Ya tengo HA instalado en una box android. Tengo o conbee2 e tengo3 bombillas (2 hue y 1 lidle) e tenho unos shellys e uno sensor de movimento de sonoff. Ya integre las bombillas y ya las puedo acender desde fuera de casa con duckdns.
Me ayudas?

Este es mi WhatsApp +3519121....

**Comment by VicenteKER** [comment]
Como lamento leer eso.... 😔😔😔

**Comment by VicenteKER** [comment]
> Bom dia.
> 
> @domoticafacilconjota decidió hace unos días dejar subir videos a youtube y ha cancelado los miembros. Te sugiero que quites el número de teléfono, en caso de que te conteste, acordar una forma de contacto. Pero no es buena idea compartir datos de contacto privados por aquí.
> 
> Por otro lado, puedes preguntar aquí tus dudas en español, portugués (nos entendemos bien, ¡creo!) o inglés. De vez en cuando yo le hecho un vistazo y contesto lo que puedo.
> 
> Un saludo.

Como lamento leer eso.... 😔😔😔

**Comment by oriol-vi** [comment]
Hola

Ya hace tiempo que utilizo el node-red, tengo muchas pestañas con diferentes sondas de temperatura.
Hago las lecturas o mediante mod bus, http request o S7. 

Desde hoy no me deja hacer un deploy, porque me da un error y no encuentro como solucionar-lo.

Dejo la version que tengo del node-red Js, etc..

"
15 Sep 13:13:18 - [info]

Welcome to Node-RED
===================

15 Sep 13:13:18 - [info] Node-RED version: v3.0.2
15 Sep 13:13:18 - [info] Node.js  version: v18.3.0
15 Sep 13:13:18 - [info] Windows_NT 10.0.19045 x64 LE
15 Sep 13:13:19 - [info] Loading palette nodes
15 Sep 13:13:21 - [info] Worldmap version 2.37.3
15 Sep 13:13:21 - [info] Dashboard version 3.2.0 started at /ui
15 Sep 13:13:22 - [info] Settings file  : C:\Users\admin\.node-red\settings.js
15 Sep 13:13:22 - [info] Context store  : 'default' [module=memory]
15 Sep 13:13:22 - [info] User directory : \Users\admin\.node-red
15 Sep 13:13:22 - [warn] Projects disabled : editorTheme.projects.enabled=false
15 Sep 13:13:22 - [warn] Flows file name not set. Generating name using hostname.
15 Sep 13:13:22 - [info] Flows file     : \Users\admin\.node-red\flows_IOT.json
15 Sep 13:13:22 - [info] Server now running at http://127.0.0.1:1880/
15 Sep 13:13:22 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

15 Sep 13:13:28 - [info] Starting flows

"

También, dejo una copia del error que me envia a la hora de hacer un deploy

"
PayloadTooLargeError: request entity too large
    at readStream (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\raw-body\index.js:157:17)
    at getRawBody (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\raw-body\index.js:109:12)
    at read (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\body-parser\lib\read.js:79:3)
    at jsonParser (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\body-parser\lib\types\json.js:135:5)
    at Layer.handle [as handle_request] (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\express\lib\router\index.js:280:10)
    at cors (C:\Users\admin\AppData\Roaming\npm\node_modules\node-red\node_modules\cors\lib\index.js:188:7)
"
Nada más, si alguien sabe como solucionar-lo, estaría muy agradecido.!!
